# Theme
remote_theme: pmarsceill/just-the-docs

# Main
title: Bitrix Kit
lang: ru
# URL
permalink: pretty

# "light" (default) and "dark"
color_scheme: dark

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

aux_links_new_tab: true

gh_edit_link: false

search_enabled: true
search:
  #preview_words_before: 3
  #preview_words_after: 3
  lang:
    - en
    - ru

plugins:
  - jekyll-seo-tag
  - search:
      lang:
        - en
        - ru

sass:
  style: :compressed
