remote_theme: pmarsceill/just-the-docs

color_scheme: light # "light" (default) and "dark"

title: Bitrix Kit

lang: ru

gh_edit_link: false

# logo: "/assets/images/just-the-docs.svg"

search_enabled: false

footer_content: Copyright &copy; 2022

# Styles
sass:
  style: :compressed

# URL
permalink: pretty
