remote_theme: pmarsceill/just-the-docs

color_scheme: light # "light" (default) and "dark"

title: Bitrix Kit

lang: ru

gh_edit_link: false

# logo: "/assets/images/just-the-docs.svg"

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

search_enabled: true
search:
  preview_words_before: 3
  preview_words_after: 3

# footer_content: Copyright &copy; 2022

plugins:
  - search:
      lang: 
        - en
        - ru


# Styles
sass:
  style: :compressed

# URL
permalink: pretty
