remote_theme: pmarsceill/just-the-docs

color_scheme: light # "light" (default) and "dark"

title: Bitrix Kit

lang: ru

gh_edit_link: false

# logo: "/assets/images/just-the-docs.svg"

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

search_enabled: true

# footer_content: Copyright &copy; 2022

# Styles
sass:
  style: :compressed

# URL
permalink: pretty
